import json
import os
import shutil
import subprocess
import tomllib
from collections.abc import Generator
from pathlib import Path
from typing import Any

import typer
from pydantic import BaseModel, Field, ValidationError
from rich.console import Console
from rich.filesize import decimal
from rich.markup import escape
from rich.progress import (
    Progress,
    TaskID,
)
from rich.text import Text
from rich.tree import Tree

app = typer.Typer(help="texi: LaTeX Project Workspace Manager")
console = Console()
tlmgr_path = shutil.which("tlmgr")
latexmk_path = shutil.which("latexmk")
texfmt_path = shutil.which("tex-fmt")

# --- Pydantic Data Models ---


class LatexmkEngines(BaseModel):
    pdf_mode: str = "pdflatex"
    dvi_mode: bool = False
    postscript_mode: bool = False


class LatexmkDirectories(BaseModel):
    out_dir: str = "build/"
    aux_dir: str = "build/aux/"


class LatexmkExecution(BaseModel):
    halt_on_error: bool = True
    bibtex_use: str = "always"
    max_repeat: int = 5


class LatexmkConfig(BaseModel):
    engines: LatexmkEngines = Field(default_factory=LatexmkEngines)
    directories: LatexmkDirectories = Field(default_factory=LatexmkDirectories)
    execution: LatexmkExecution = Field(default_factory=LatexmkExecution)


class TexProjectConfig(BaseModel):
    dependencies: list[str] = Field(default_factory=list)
    latexmk: LatexmkConfig = Field(default_factory=LatexmkConfig)


# --- Core Logic ---


def load_project_config(config_path: Path) -> TexProjectConfig:
    """Loads, parses, and validates the texproject.toml file."""
    if not config_path.exists():
        console.print(
            f"[red]Error:[/red] Configuration file '{config_path.name}' not found."
        )
        raise typer.Exit(code=1)

    try:
        raw_data = tomllib.loads(config_path.read_text(encoding="utf-8"))
        return TexProjectConfig(**raw_data)
    except tomllib.TOMLDecodeError as e:
        console.print(f"[red]TOML Parsing Error:[/red] {e}")
        raise typer.Exit(code=1)
    except ValidationError as e:
        console.print("[red]Configuration Validation Error:[/red]")
        console.print(e)
        raise typer.Exit(code=1)


def format_perl_value(key: str, value: str | int | bool | list[str]) -> str:
    """Formats Python types back to Perl latexmkrc syntax."""
    if isinstance(value, bool):
        return "1" if value else "0"

    if isinstance(value, list):
        perl_array = ", ".join(f"'{v}'" for v in value)
        return f"({perl_array})"

    if isinstance(value, str):
        # Specific enum mappings
        pdf_modes: dict[str, str] = {
            "off": "0",
            "pdflatex": "1",
            "ps2pdf": "2",
            "dvi2pdf": "3",
            "lualatex": "4",
            "xelatex": "5",
        }
        bibtex_modes: dict[str, str] = {
            "never": "0",
            "bib_exists": "1",
            "even_without_bib": "1.5",
            "always": "2",
        }

        if key == "pdf_mode" and value in pdf_modes:
            return pdf_modes[value]
        if key == "bibtex_use" and value in bibtex_modes:
            return bibtex_modes[value]

        return f"'{value}'"

    return str(value)


def generate_latexmkrc(config: TexProjectConfig, rc_path: Path) -> None:
    """Generates a .latexmkrc file from the validated Pydantic model."""
    rc_lines: list[str] = ["# Auto-generated by texi.", "# Do not edit manually.", ""]

    # model_dump() converts the nested models into a dictionary
    config_dict = config.latexmk.model_dump()

    for section_name, settings in config_dict.items():
        rc_lines.append(f"# --- {section_name.capitalize()} ---")
        for key, value in settings.items():
            if value is None:
                continue

            perl_val = format_perl_value(key, value)
            prefix = "@" if isinstance(value, list) else "$"
            rc_lines.append(f"{prefix}{key} = {perl_val};")
        rc_lines.append("")

    rc_path.write_text("\n".join(rc_lines), encoding="utf-8")


def _tlmgr_info(*cmd_input: list[str]) -> subprocess.CompletedProcess:
    """Runs tlmgr info with the given input and returns the completed process."""
    cmd: list[str] = [
        tlmgr_path,
        "info",
        *cmd_input,
    ]
    return subprocess.run(cmd, capture_output=True, text=True, check=False)


def _parse_tlmgr_info_output(
    result: subprocess.CompletedProcess, fields: list[str]
) -> Generator[dict[str, Any | str] | dict[str, Any], Any, None]:
    expected_seperators = len(fields) - 1
    output_lines = result.stdout.splitlines() + result.stderr.splitlines()
    for line in output_lines:
        if "not found neither locally nor remote" in line:
            parts = line.split()
            if len(parts) >= 3:
                pkg_name = parts[2]
                yield {
                    "name": pkg_name,
                    "status": "missing",
                }
        elif "not locally!" in line:  # tlmgr: package acmart not locally!
            parts = line.split()
            if len(parts) >= 3:
                pkg_name = parts[2]
                yield {"name": pkg_name, "status": "not_locally"}
        elif (
            line.count(",") == expected_seperators
        ):  # Expecting lines like "pkgname,installed,relocatable,size"
            parts = line.strip().split(",")
            if len(parts) != len(fields):
                yield {
                    "status": "unexpected",
                    "line": line,
                    "error": f"Expected {len(fields)} fields but got {len(parts)}",
                }
                continue
            parsed_fields = dict(zip(fields, parts, strict=True))
            if "installed" in parsed_fields:
                parsed_fields["installed"] = parsed_fields["installed"] == "1"
            if "relocatable" in parsed_fields:
                parsed_fields["relocatable"] = parsed_fields["relocatable"] == "1"
            yield parsed_fields | {"status": "found"}

        else:
            yield {"status": "unexpected", "line": line}


def _get_tlmgr_info_output(
    *cmd_input: list[str], data_fields: list[str], env_dir: Path
) -> Generator[dict[str, Any | str] | dict[str, Any], Any, None]:
    tlmgr_result = _tlmgr_info(
        "--usertree",
        str(env_dir),
        "--data",
        ",".join(data_fields),
        *cmd_input,
    )
    return _parse_tlmgr_info_output(tlmgr_result, data_fields)


def filter_packages(
    packages: list[str], env_dir: Path, progress: Progress, task_id: TaskID
) -> tuple[list[str], list[str], list[str]]:
    """
    Queries tlmgr via JSON to categorize packages into valid (to install),
    skipped (system binaries), and already installed.
    """
    if not packages:
        return [], [], []

    packages = list(set(packages))  # Deduplicate
    progress.update(
        task_id,
        total=len(packages),
    )
    installable_local_packages: list[str] = []
    installable_system_packages: list[str] = []
    already_installed: list[str] = []
    remote_packages: list[str] = []
    missing_packages: list[str] = []

    data_fields = ["name", "installed", "relocatable"]

    # TODO: should the "--usermode" flag be included?
    installed_result = _get_tlmgr_info_output(
        "--only-installed", *packages, data_fields=data_fields, env_dir=env_dir
    )
    for result in installed_result:
        if result["status"] == "found":
            if result["installed"]:
                already_installed.append(result["name"])
            elif not result["installed"] and result["relocatable"]:
                installable_local_packages.append(result["name"])
            elif not result["installed"] and not result["relocatable"]:
                installable_system_packages.append(result["name"])
            progress.advance(task_id, 1)
        elif result["status"] == "missing":
            console.print(
                f"[yellow]Warning: Package '{result['name']}' is not available in the current TeX Live repository.[/yellow]"
            )
            missing_packages.append(result["name"])
            progress.advance(task_id, 1)
        elif result["status"] == "not_locally":
            remote_packages.append(result["name"])
            progress.advance(task_id, 1)
        elif result["status"] == "unexpected":
            console.print(
                f"[red]Unexpected output from tlmgr info: {result.get('line', '')}[/red]"
            )

    remaining_packages = list(set(missing_packages + remote_packages))

    remote_result = _get_tlmgr_info_output(
        "--only-remote", *remaining_packages, data_fields=data_fields, env_dir=env_dir
    )
    for result in remote_result:
        if result["status"] == "found":
            if result["installed"]:
                already_installed.append(result["name"])
            elif not result["installed"] and result["relocatable"]:
                installable_local_packages.append(result["name"])
            elif not result["installed"] and not result["relocatable"]:
                installable_system_packages.append(result["name"])
            progress.advance(task_id, 1)
        elif result["status"] == "missing":
            console.print(
                f"[yellow]Warning: Package '{result['name']}' is not available in the current TeX Live repository.[/yellow]"
            )
            missing_packages.append(result["name"])
            progress.advance(task_id, 1)
        elif result["status"] == "not_locally":
            remote_packages.append(result["name"])
            progress.advance(task_id, 1)
        elif result["status"] == "unexpected":
            console.print(
                f"[red]Unexpected output from tlmgr info: {result.get('line', '')}[/red]"
            )

    installable_local_packages = list(set(installable_local_packages))
    installable_system_packages = list(set(installable_system_packages))
    already_installed = list(set(already_installed))

    return installable_local_packages, installable_system_packages, already_installed


def find_bundle_for_sty(sty_name: str, console: Console) -> list[str]:
    """
    Searches CTAN via tlmgr to find which package bundles
    provide the exact {sty_name}.sty file.
    """
    cmd: list[str] = [
        "tlmgr",
        "search",
        sty_name,
        "--json",
        "--word",
        "--global",
        "--file",
    ]

    try:
        # We drop check=True so we can handle tlmgr's exit codes manually if needed,
        # but here we just want to suppress outright crashes.
        result = subprocess.run(cmd, capture_output=True, text=True, check=False)
        # if result.returncode != 0 and not result.stdout.strip():
        #     return []
        # console.print(f"[dim]tlmgr search output: {result.stdout}[/dim]")
        output = result.stdout.strip()

        if not output.startswith("{"):
            # Find the index of the first opening curly brace
            start_index = output.find("{")

            if start_index != -1:
                # Slice the string from the first '{' to the end
                output = output[start_index:]
        data = json.loads(output)
    except (subprocess.CalledProcessError, json.JSONDecodeError):
        console.print_exception()
        console.print(output)
        return []

    matched_bundles: list[str] = []

    # We look for paths ending in /name.sty to avoid false positives
    target_suffix = f"/{sty_name}.sty"
    exact_match = f"{sty_name}.sty"

    files_dict: dict[str, list[str]] = data.get("files", {})

    for bundle_name, file_paths in files_dict.items():
        for path in file_paths:
            if path.endswith(target_suffix) or path == exact_match:
                matched_bundles.append(bundle_name)
                break  # Found it in this bundle, skip remaining files in this bundle

    return matched_bundles


# --- CLI Commands ---


@app.command()
def sync() -> None:
    r"""Creates a local texmf tree and installs project dependencies.
    fieldname "\t" value
    ...
    "end-of-header"
    pkgname status localrev serverrev size runtime esttot
    ...
    "end-of-updates"
    other output from post actions, not in machine readable form
    The header section currently has two fields: location-url (the repository source from which updates are being drawn), and total-bytes (the total number of bytes to be downloaded).

    The localrev and serverrev fields for each package are the revision numbers in the local installation and server repository, respectively. The size field is the number of bytes to be downloaded, i.e., the size of the compressed tar file for a network installation, not the unpacked size. The runtime and esttot fields are only present for updated and auto-install packages, and contain the currently passed time since start of installation/updates and the estimated total time.


    --command-logfile file
    --package-logfile file
    """
    cwd = Path.cwd()
    config = load_project_config(cwd / "texproject.toml")
    env_dir = cwd / ".texenv"

    if not config.dependencies:
        console.print(
            "[yellow]No dependencies found in texproject.toml. Nothing to sync.[/yellow]"
        )
        return

    env_dir.mkdir(exist_ok=True)

    # Path to the local database file that proves initialization
    tlpdb_path = env_dir / "tlpkg" / "texlive.tlpdb"

    with Progress(
        # SpinnerColumn(),
        # BarColumn(),
        # TaskProgressColumn(),
        # TimeRemainingColumn(),
        *Progress.get_default_columns(),
        # TextColumn("[progress.description]{task.description}"),
        # transient=True,
        console=console,
    ) as progress:
        if tlpdb_path.exists():
            progress.console.print(
                "[green]Local usertree already initialized. Skipping initialization...[/green]"
            )
        else:
            tree_task = progress.add_task(
                description="Initializing local usertree...", total=None
            )
            # Use Popen to stream stdout and stderr (merged via STDOUT) in real-time
            init_process = subprocess.Popen(
                [
                    tlmgr_path,
                    "init-usertree",
                    "--usertree",
                    str(env_dir),
                ],
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
            )

            # Use progress.console.print so logs don't corrupt the live progress bar
            for line in init_process.stdout:
                progress.console.print(line.strip())

            if init_process.wait() == 0:
                progress.console.print("[green]Initialization successful![/green]")
            else:
                progress.console.print("[red]Initialization failed![/red]")
                raise typer.Exit(code=1)
            progress.remove_task(tree_task)

        # Filter out binaries like latexmk, pdftex, etc.
        # progress.console.print("Fetching package metadata...")
        metadata_task = progress.add_task(
            description=f"Fetching metadata for {len(config.dependencies)} packages...",
            total=None,
        )
        progress.console.print(f"[dim]{', '.join(config.dependencies)}[/dim]")
        valid_dependencies, system_dependencies, already_installed = filter_packages(
            config.dependencies, env_dir, progress, metadata_task
        )
        progress.remove_task(metadata_task)
        all_dependencies = set(valid_dependencies + system_dependencies)
        progress.console.print(
            f"[dim]Skipping {len(already_installed)} already installed packages: {', '.join(already_installed)}[/dim]"
        )
        install_task = progress.add_task(
            description=f"Installing {len(valid_dependencies)} packages...",
            total=None,
        )
        progress.console.print(
            f"[dim]Installing {len(valid_dependencies)} relocatable packages: {', '.join(valid_dependencies)}[/dim]"
        )

        cmd: list[str] = [
            tlmgr_path,
            "install",
            "--usertree",
            str(env_dir),
            "--usermode",
            *valid_dependencies,
            "--machine-readable",
        ]

        progress.console.print("[dim]Installing packages with tlmgr...[/dim]")
        install_process = subprocess.Popen(
            cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True
        )

        # install_process.
        ignore_output = False
        total = None
        for line in install_process.stdout:
            stripped_line = line.strip()
            if stripped_line.startswith("total-bytes"):
                parts = stripped_line.split("\t")
                if len(parts) >= 2:
                    total_bytes = parts[1]
                    # progress.console.print(
                    #     f"[dim]Total bytes to download: {total_bytes}[/dim]"
                    # )
                    total = int(total_bytes)
                    progress.update(install_task, total=total)
                    # progress.remove_task(install_task)
                    # install_task = progress.add_task(
                    #     description=f"Installing {len(valid_dependencies)} packages...\n",
                    #     total=total,
                    # )
            if "is not relocatable, cannot install it in user mode!" in stripped_line:
                parts = stripped_line.split()
                if len(parts) >= 2:
                    pkg_name = parts[2]
                    progress.console.print(
                        f"[yellow]Warning: Package '{pkg_name}' is not relocatable and cannot be installed in user mode. Skipping.[/yellow]"
                    )
                    # system_dependencies.append(pkg_name)

            if not ignore_output:
                # progress.console.print(stripped_line)
                if stripped_line.count("\t") == 9:
                    # progress.console.print(stripped_line.count("\t"))
                    parts = stripped_line.split("\t")
                    # progress.console.print(f"[dim]Parsed parts: {parts}[/dim]")
                    progress.advance(install_task, int(parts[4]))

            if stripped_line == "end-of-updates":
                # progress.update(install_task, completed=100)
                # progress.update(install_task, completed=total)
                progress.update(
                    install_task,
                    description="Running post-installation scripts...",
                    total=None,
                )
                ignore_output = True

        # if install_process.wait() != 0:
        # progress.console.print("[red]Package installation failed![/red]")
        # raise typer.Exit(code=1)
        # progress.update(install_task, completed=100)
        progress.console.print(
            f"[green]✔ Successfully synced {len(valid_dependencies)} dependencies into .texenv/[/green]"
            f"\n[dim]{', '.join(valid_dependencies)}[/dim]"
        )

        install_task = progress.add_task(
            description=f"Installing {len(system_dependencies)} system packages...\n[dim]{', '.join(system_dependencies)}[/dim]",
            total=None,
        )

        cmd: list[str] = [
            "tlmgr",
            "install",
            *system_dependencies,
            "--machine-readable",
        ]

        progress.console.print("[dim]Installing system packages with tlmgr...[/dim]")
        install_process = subprocess.Popen(
            cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True
        )

        ignore_output = False
        total = None
        for line in install_process.stdout:
            stripped_line = line.strip()
            if stripped_line.startswith("total-bytes"):
                parts = stripped_line.split("\t")
                if len(parts) >= 2:
                    total_bytes = parts[1]
                    progress.console.print(
                        f"[dim]Total bytes to download: {total_bytes}[/dim]"
                    )
                    total = int(total_bytes)
                    progress.update(install_task, total=total)
            if "is not relocatable, cannot install it in user mode!" in stripped_line:
                parts = stripped_line.split()
                if len(parts) >= 2:
                    pkg_name = parts[2]
                    progress.console.print(
                        f"[yellow]Warning: Package '{pkg_name}' is not relocatable and cannot be installed in user mode. Skipping.[/yellow]"
                    )
                    # system_dependencies.append(pkg_name)

            if not ignore_output:
                progress.console.print(stripped_line)
                if stripped_line.count("\t") == 9:
                    # progress.console.print(stripped_line.count("\t"))
                    parts = stripped_line.split("\t")
                    # progress.console.print(f"[dim]Parsed parts: {parts}[/dim]")
                    progress.advance(install_task, int(parts[4]))
                elif stripped_line.count("\t") >= 2:
                    progress.console.print(
                        f"[red]Unexpected tab output: {stripped_line}[/red]"
                    )

            if stripped_line == "end-of-updates":
                progress.update(
                    install_task,
                    description="Running post-installation scripts...",
                    total=None,
                )

                ignore_output = True

    progress.update(
        install_task, completed=len(all_dependencies), total=len(all_dependencies)
    )
    progress.console.print(
        f"[green]✔ Successfully synced {len(all_dependencies)} dependencies into .texenv/[/green]"
        f"\n[dim]{', '.join([pkg[0] for pkg in all_dependencies])}[/dim]"
    )


@app.command()
def build() -> None:
    """Generates .latexmkrc and compiles the project."""
    cwd = Path.cwd()
    env_dir = cwd / ".texenv"

    output_file = cwd / "build" / "main.pdf"
    if output_file.exists():
        console.print(f"[dim]Removing existing output file: {output_file}[/dim]")
        output_file.unlink()

    load_project_config(cwd / "texproject.toml")
    # generate_latexmkrc(config, cwd / ".latexmkrc")
    console.print("[dim]Generated .latexmkrc from texproject.toml[/dim]")

    env = os.environ.copy()
    if env_dir.exists():
        env["TEXMFHOME"] = str(env_dir.resolve())
        env["max_print_line"] = "100000"  # Avoid line wrapping in logs
        console.print("[dim]Using local .texenv for compilation[/dim]")
    else:
        console.print(
            "[yellow]Warning: .texenv not found. Run `texi sync` for isolated dependencies.[/yellow]"
        )

    console.print("[bold blue]Starting latexmk...[/bold blue]\n")
    try:
        subprocess.run(
            ["latexmk"], env=env, check=True, capture_output=False, text=True
        )
        console.print("\n[green]✔ Build completed successfully![/green]")
    except subprocess.CalledProcessError as e:
        console.print("\n[red]✖ Build failed. Check the logs above.[/red]")
        console.print(f"[dim]{e.stderr}[/dim]")
        raise typer.Exit(code=1) from e


@app.command()
def tree(project_dir: Path | None = None, fls_filename: str = "main.fls") -> None:
    if project_dir is None:
        project_dir = Path.cwd()
    fls_path = project_dir / "build" / "aux" / fls_filename
    if not fls_path.exists():
        console.print(
            f"Error: {fls_filename} not found. Is your project built? Did you specify the correct filename (default: main.fls)?"
        )
        return

    # Parse the .fls file for used inputs
    used_files: set[Path] = set()
    used_folders: set[Path] = set()
    with fls_path.open("r", encoding="utf-8") as f:
        for line in f:
            if line.startswith("INPUT "):
                raw_path = line.removeprefix("INPUT ").strip()
                # Resolve creates an absolute path, normalizing relative dots
                used_files.add(Path(raw_path).resolve())
                used_folders.add(Path(raw_path).parent.resolve())

    def walk_directory(current_dir: Path, tree: Tree) -> None:
        # Sort dirs first then by filename
        paths = sorted(
            Path(current_dir).iterdir(),
            key=lambda path: (path.is_file(), path.name.lower()),
        )
        for path in paths:
            # Remove hidden files
            if path.name.startswith("."):
                continue
            if path.is_dir() and path.resolve() in used_folders:
                style = "dim" if path.name.startswith("__") else ""
                branch = tree.add(
                    f"[bold magenta]:open_file_folder: [link file://{path}]{escape(path.name)}",
                    style=style,
                    guide_style=style,
                )
                walk_directory(path, branch)
            elif path.is_file() and path.resolve() in used_files:
                text_filename = Text(path.name, "green")
                text_filename.highlight_regex(r"\..*$", "bold red")
                text_filename.stylize(f"link file://{path}")
                file_size = path.stat().st_size
                text_filename.append(f" ({decimal(file_size)})", "blue")
                icon = "🐍 " if path.suffix == ".py" else "📄 "
                tree.add(Text(icon) + text_filename)

    tree = Tree(
        f":open_file_folder: [link file://{project_dir.resolve()}]{project_dir}",
        guide_style="bold bright_blue",
    )
    walk_directory(project_dir, tree)
    console.print(tree)

@app.command()
def info():
    """Displays information about the current texi environment."""
    cwd = Path.cwd()
    env_dir = cwd / ".texenv"
    tlpdb_path = env_dir / "tlpkg" / "texlive.tlpdb"

    if not tlpdb_path.exists():
        console.print(
            "[yellow]Warning: .texenv not found. Run `texi sync` to initialize the environment.[/yellow]"
        )
        return

    console.print(f"[bold blue]Current texi environment info:[/bold blue]")
    console.print(f"Environment directory: {env_dir.resolve()}")
    console.print(f"TLPDB path: {tlpdb_path.resolve()}")
    console.print(f"Tlmgr path: {tlmgr_path}")
    console.print(f"Latexmk path: {latexmk_path}")
    console.print(f"Tex-fmt path: {texfmt_path}")

if __name__ == "__main__":
    app()
