import json
import operator
import os
import subprocess
import tomllib
from pathlib import Path

import typer
from pydantic import BaseModel, Field, ValidationError
from rich.console import Console
from rich.progress import (
    Progress,
    TaskID,
)

app = typer.Typer(help="texi: LaTeX Project Workspace Manager")
console = Console()

# --- Pydantic Data Models ---


class LatexmkEngines(BaseModel):
    pdf_mode: str = "pdflatex"
    dvi_mode: bool = False
    postscript_mode: bool = False


class LatexmkDirectories(BaseModel):
    out_dir: str = "build/"
    aux_dir: str = "build/aux/"


class LatexmkExecution(BaseModel):
    halt_on_error: bool = True
    bibtex_use: str = "always"
    max_repeat: int = 5


class LatexmkConfig(BaseModel):
    engines: LatexmkEngines = Field(default_factory=LatexmkEngines)
    directories: LatexmkDirectories = Field(default_factory=LatexmkDirectories)
    execution: LatexmkExecution = Field(default_factory=LatexmkExecution)


class TexProjectConfig(BaseModel):
    dependencies: list[str] = Field(default_factory=list)
    latexmk: LatexmkConfig = Field(default_factory=LatexmkConfig)


# --- Core Logic ---


def load_project_config(config_path: Path) -> TexProjectConfig:
    """Loads, parses, and validates the texproject.toml file."""
    if not config_path.exists():
        console.print(
            f"[red]Error:[/red] Configuration file '{config_path.name}' not found."
        )
        raise typer.Exit(code=1)

    try:
        raw_data = tomllib.loads(config_path.read_text(encoding="utf-8"))
        return TexProjectConfig(**raw_data)
    except tomllib.TOMLDecodeError as e:
        console.print(f"[red]TOML Parsing Error:[/red] {e}")
        raise typer.Exit(code=1)
    except ValidationError as e:
        console.print("[red]Configuration Validation Error:[/red]")
        console.print(e)
        raise typer.Exit(code=1)


def format_perl_value(key: str, value: str | int | bool | list[str]) -> str:
    """Formats Python types back to Perl latexmkrc syntax."""
    if isinstance(value, bool):
        return "1" if value else "0"

    if isinstance(value, list):
        perl_array = ", ".join(f"'{v}'" for v in value)
        return f"({perl_array})"

    if isinstance(value, str):
        # Specific enum mappings
        pdf_modes: dict[str, str] = {
            "off": "0",
            "pdflatex": "1",
            "ps2pdf": "2",
            "dvi2pdf": "3",
            "lualatex": "4",
            "xelatex": "5",
        }
        bibtex_modes: dict[str, str] = {
            "never": "0",
            "bib_exists": "1",
            "even_without_bib": "1.5",
            "always": "2",
        }

        if key == "pdf_mode" and value in pdf_modes:
            return pdf_modes[value]
        if key == "bibtex_use" and value in bibtex_modes:
            return bibtex_modes[value]

        return f"'{value}'"

    return str(value)


def generate_latexmkrc(config: TexProjectConfig, rc_path: Path) -> None:
    """Generates a .latexmkrc file from the validated Pydantic model."""
    rc_lines: list[str] = ["# Auto-generated by texi.", "# Do not edit manually.", ""]

    # model_dump() converts the nested models into a dictionary
    config_dict = config.latexmk.model_dump()

    for section_name, settings in config_dict.items():
        rc_lines.append(f"# --- {section_name.capitalize()} ---")
        for key, value in settings.items():
            if value is None:
                continue

            perl_val = format_perl_value(key, value)
            prefix = "@" if isinstance(value, list) else "$"
            rc_lines.append(f"{prefix}{key} = {perl_val};")
        rc_lines.append("")

    rc_path.write_text("\n".join(rc_lines), encoding="utf-8")


# --- CLI Commands ---


def filter_relocatable_packages(packages: list[str]) -> list[str]:
    """Queries tlmgr to remove non-relocatable packages (like binaries) from the install list."""
    if not packages:
        return []

    cmd: list[str] = ["tlmgr", "info", "--data", "name,relocatable", *packages]

    console.print(" ".join(cmd))
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=False)
    except subprocess.CalledProcessError as e:
        console.print("[red]Failed to query package metadata from tlmgr.[/red]")
        console.print(f"[dim]{e.stderr}[/dim]")
        raise typer.Exit(code=1)

    valid_packages: list[str] = []
    skipped_packages: list[str] = []

    for line in result.stdout.strip().splitlines():
        parts = line.split(",")
        if len(parts) == 2:
            pkg_name, is_relocatable = parts
            if is_relocatable == "1":
                valid_packages.append(pkg_name)
            else:
                skipped_packages.append(pkg_name)

    missing_packages: list[str] = []
    for line in result.stderr.strip().splitlines():
        console.print(f"[dim]{line}[/dim]")
        if "not found neither locally nor remote" in line:
            parts = line.split()
            if len(parts) >= 3:
                missing_packages.append(parts[2])

    if skipped_packages:
        console.print(
            f"[dim]Skipping system binaries (non-relocatable): {', '.join(skipped_packages)}[/dim]"
        )

    return valid_packages, skipped_packages


def filter_packages(
    packages: list[str], env_dir: Path, progress: Progress, task_id: TaskID
) -> tuple[list[str], list[str], list[str]]:
    """
    Queries tlmgr via JSON to categorize packages into valid (to install),
    skipped (system binaries), and already installed.
    """
    if not packages:
        return [], [], []
    console = progress.console
    progress.update(
        task_id,
        total=len(packages),
    )
    valid_packages: list[str] = []
    system_packages: list[str] = []
    already_installed: list[str] = []

    data_fields = "name,installed,relocatable"
    data_fields.count(",")
    cmd: list[str] = [
        "tlmgr",
        "info",
        "--usertree",
        str(env_dir),
        # "--usermode", # omit?
        # "--json", # --data name,relocatable
        "--data",
        data_fields,  # ,size
        # name,category,localrev,remoterev,installed,size,relocatable,depends,cat-version,cat-date
        "--only-installed",
        *packages,
    ]

    # Run without check=True to manually intercept missing package errors
    result = subprocess.run(cmd, capture_output=True, text=True)

    # console.print(f"[dim]tlmgr info output: {result.stdout}[/dim]")
    # console.print(f"[dim]tlmgr err output: {result.stderr}[/dim]")
    # 1. Intercept missing packages from stderr
    missing_packages = []
    remote_packages = []
    output_lines = result.stdout.splitlines() + result.stderr.splitlines()
    for line in output_lines:
        if "not found neither locally nor remote" in line:
            parts = line.split()
            if len(parts) >= 3:
                missing_packages.append(parts[2])
                # progress.advance(task_id, 1)
        elif "not locally!" in line:  # tlmgr: package acmart not locally!
            parts = line.split()
            if len(parts) >= 3:
                remote_packages.append(parts[2])
                # progress.advance(task_id, 1)

                console.print(f"[orange] ❗ Not installed: {parts[2]}[/orange]")
        elif (
            line.count(",") == 2
        ):  # Expecting lines like "pkgname,installed,relocatable,size"
            # console.print(f"[dim]{line}[/dim]")
            parts = line.strip().split(",")
            pkg_name, installed, relocatable = (
                parts[0],
                parts[1],
                parts[2],
                # parts[3],
            )
            # size = int(size) if size.isdigit() else 0
            size = 0
            if installed == "1":
                already_installed.append((pkg_name, size))
                console.print(f"[green] ✔ Already installed: {pkg_name}[/green]")
                progress.advance(task_id, 1)

            elif installed == "0" and relocatable == "1":
                console.print(
                    f"[orange] ❗ Not installed but relocatable: {pkg_name}[/orange]"
                )
                valid_packages.append((pkg_name, size))
            elif installed == "0" and relocatable == "0":
                console.print(
                    f"[red] ❗ Not installed and not relocatable: {pkg_name}[/red]"
                )
                system_packages.append((pkg_name, size))
        else:
            console.print(f"[red]Unexpected output: {line}[/red]")

    remaining_packages = list(set(missing_packages + remote_packages))
    cmd: list[str] = [
        "tlmgr",
        "info",
        "--usertree",
        str(env_dir),
        # "--usermode", # omit?
        # "--json", # --data name,relocatable
        "--data",
        "name,installed,relocatable",  # ,size
        # name,category,localrev,remoterev,installed,size,relocatable,depends,cat-version,cat-date
        # "--only-installed",
        "--only-remote",
        *remaining_packages,
    ]

    # Run without check=True to manually intercept missing package errors
    result = subprocess.run(cmd, capture_output=True, text=True)
    console.print(f"[dim]tlmgr info output: {result.stdout}[/dim]")
    console.print(f"[dim]tlmgr err output: {result.stderr}[/dim]")
    # 1. Intercept missing packages from stderr
    # missing_packages = []
    # remote_packages = []
    output_lines = result.stdout.splitlines() + result.stderr.splitlines()
    for line in output_lines:
        if "not found neither locally nor remote" in line:
            parts = line.split()
            console.print(f"[dim]{line}[/dim]")
            if len(parts) >= 3:
                missing_packages.append(parts[2])
                progress.advance(task_id, 1)

                pkg_name = parts[2]
                bundle = find_bundle_for_sty(pkg_name, console)
                console.print(
                    f"[yellow]Warning: Package '{pkg_name}' is not available in the current TeX Live repository. Did you mean '{"', or '".join(bundle)}'?[/yellow]"
                )
        elif "not locally!" in line:  # tlmgr: package acmart not locally!
            parts = line.split()
            if len(parts) >= 3:
                remote_packages.append(parts[2])
                progress.advance(task_id, 1)
        elif line.count(",") == 2:
            # console.print(f"[dim]{line}[/dim]")
            parts = line.strip().split(",")
            # console.print(f"[magenta]{parts}[/magenta]")

            # pkg_name, installed, relocatable, size = (
            #     parts[0],
            #     parts[1],
            #     parts[2],
            #     parts[3],
            # )
            # size = int(size) if size.isdigit() else 0
            pkg_name, installed, relocatable = (
                parts[0],
                parts[1],
                parts[2],
            )
            size = 0
            progress.advance(task_id, 1)

            if installed == "1":
                already_installed.append((pkg_name, size))
                console.print(f"[green] ✔ Already installed: {pkg_name}[/green]")
            elif installed == "0" and relocatable == "1":
                console.print(
                    f"[orange] ❗ Not installed but relocatable: {pkg_name}[/orange]"
                )
                valid_packages.append((pkg_name, size))
            elif installed == "0" and relocatable == "0":
                console.print(
                    f"[red] ❗ Not installed and not relocatable: {pkg_name}[/red]"
                )
                system_packages.append((pkg_name, size))
        else:
            console.print(f"[red]Unexpected output: {line}[/red]")

    # if missing_packages:
    #     console.print("[red]✖ Error: Some packages could not be found on CTAN.[/red]")
    #     console.print(
    #         "[yellow]Note: TeX Live uses package *bundle* names, which don't always match the .sty filename![/yellow]"
    #     )
    #     console.print(
    #         f"\n[bold red]Please update these names in your texproject.toml:[/bold red] {', '.join(missing_packages)}"
    #     )
    #     raise typer.Exit(code=1)

    # 2. Parse the JSON from stdout

    # try:
    #     package_data = json.loads(result.stdout)
    #     # console.print(package_data)
    #     for pkg in package_data:
    #         pkg_name = pkg.get("name", "")
    #         is_installed = pkg.get("installed", False)
    #         # tlmgr JSON uses the key "relocated" for relocatable packages
    #         is_relocatable = pkg.get("relocated", False)
    #         is_available = pkg.get("available", False)
    #         if not is_available:
    #             bundle = find_bundle_for_sty(pkg_name, console)
    #             console.print(
    #                 f"[yellow]Warning: Package '{pkg_name}' is not available in the current TeX Live repository. Did you mean {"', or '".join(bundle)}?[/yellow]"
    #             )

    #             # skipped_packages.append(pkg_name)
    #             continue
    #         if is_installed:
    #             already_installed.append(pkg_name)
    #         elif is_relocatable:
    #             valid_packages.append(pkg_name)
    #         else:
    #             system_packages.append(pkg_name)
    #         # else:
    #         # skipped_packages.append(pkg_name)

    # except json.JSONDecodeError:
    #     console.print("[red]Failed to parse JSON output from tlmgr.[/red]")
    #     console.print(f"[dim]{result.stdout}[/dim]")
    #     raise typer.Exit(code=1)

    # if system_packages:
    #     console.print(
    #         f"[dim]Skipping system binaries (non-relocatable): {', '.join(system_packages)}[/dim]"
    #     )

    if already_installed:
        console.print(
            f"[dim]Already installed (skipping): {', '.join([pkg[0] for pkg in already_installed])}[/dim]"
        )

    valid_packages = list(set(valid_packages))
    system_packages = list(set(system_packages))
    already_installed = list(set(already_installed))

    return valid_packages, system_packages, already_installed


def find_bundle_for_sty(sty_name: str, console: Console) -> list[str]:
    """
    Searches CTAN via tlmgr to find which package bundles
    provide the exact {sty_name}.sty file.
    """
    cmd: list[str] = [
        "tlmgr",
        "search",
        sty_name,
        "--json",
        "--word",
        "--global",
        "--file",
    ]

    try:
        # We drop check=True so we can handle tlmgr's exit codes manually if needed,
        # but here we just want to suppress outright crashes.
        result = subprocess.run(cmd, capture_output=True, text=True)
        # if result.returncode != 0 and not result.stdout.strip():
        #     return []
        # console.print(f"[dim]tlmgr search output: {result.stdout}[/dim]")
        output = result.stdout.strip()

        if not output.startswith("{"):
            # Find the index of the first opening curly brace
            start_index = output.find("{")

            if start_index != -1:
                # Slice the string from the first '{' to the end
                output = output[start_index:]
        data = json.loads(output)
    except (subprocess.CalledProcessError, json.JSONDecodeError):
        console.print_exception()
        console.print(output)
        return []

    matched_bundles: list[str] = []

    # We look for paths ending in /name.sty to avoid false positives
    target_suffix = f"/{sty_name}.sty"
    exact_match = f"{sty_name}.sty"

    files_dict: dict[str, list[str]] = data.get("files", {})

    for bundle_name, file_paths in files_dict.items():
        for path in file_paths:
            if path.endswith(target_suffix) or path == exact_match:
                matched_bundles.append(bundle_name)
                break  # Found it in this bundle, skip remaining files in this bundle

    return matched_bundles


@app.command()
def sync() -> None:
    r"""Creates a local texmf tree and installs project dependencies.
    fieldname "\t" value
    ...
    "end-of-header"
    pkgname status localrev serverrev size runtime esttot
    ...
    "end-of-updates"
    other output from post actions, not in machine readable form
    The header section currently has two fields: location-url (the repository source from which updates are being drawn), and total-bytes (the total number of bytes to be downloaded).

    The localrev and serverrev fields for each package are the revision numbers in the local installation and server repository, respectively. The size field is the number of bytes to be downloaded, i.e., the size of the compressed tar file for a network installation, not the unpacked size. The runtime and esttot fields are only present for updated and auto-install packages, and contain the currently passed time since start of installation/updates and the estimated total time.


    --command-logfile file
    --package-logfile file
    """
    cwd = Path.cwd()
    config = load_project_config(cwd / "texproject.toml")
    env_dir = cwd / ".texenv"

    if not config.dependencies:
        console.print(
            "[yellow]No dependencies found in texproject.toml. Nothing to sync.[/yellow]"
        )
        return

    env_dir.mkdir(exist_ok=True)

    # Path to the local database file that proves initialization
    tlpdb_path = env_dir / "tlpkg" / "texlive.tlpdb"

    with Progress(
        # SpinnerColumn(),
        # BarColumn(),
        # TaskProgressColumn(),
        # TimeRemainingColumn(),
        *Progress.get_default_columns(),
        # TextColumn("[progress.description]{task.description}"),
        # transient=True,
        console=console,
    ) as progress:
        if tlpdb_path.exists():
            progress.console.print(
                "[green]Local usertree already initialized. Skipping initialization...[/green]"
            )
        else:
            tree_task = progress.add_task(
                description="Initializing local usertree...", total=None
            )
            # Use Popen to stream stdout and stderr (merged via STDOUT) in real-time
            init_process = subprocess.Popen(
                [
                    "tlmgr",
                    "init-usertree",
                    "--usertree",
                    str(env_dir),
                ],
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
            )

            # Use progress.console.print so logs don't corrupt the live progress bar
            for line in init_process.stdout:
                progress.console.print(line.strip())

            if init_process.wait() == 0:
                progress.console.print("[green]Initialization successful![/green]")
            else:
                progress.console.print("[red]Initialization failed![/red]")
                raise typer.Exit(code=1)
            progress.remove_task(tree_task)
            # try:
            #     # Switched to capture_output so we can surface the actual error to the user
            #     subprocess.run(
            #         ["tlmgr", "init-usertree", "--usertree", str(env_dir)],
            #         check=True,
            #         capture_output=True,
            #         text=True,
            #     )
            # except subprocess.CalledProcessError as e:
            #     console.print("\n[red]✖ Failed to initialize local usertree.[/red]")
            #     # Print exactly why it failed (e.g., missing xzdec, permission denied)
            #     console.print(f"[dim]{e.stderr or e.stdout}[/dim]")
            #     raise typer.Exit(code=1)

        # progress.add_task(description="Initializing local usertree...", total=None)
        # subprocess.run(
        #     ["tlmgr", "init-usertree", "--usertree", str(env_dir), "--machine-readable"],
        #     check=True,
        #     stdout=subprocess.DEVNULL,
        #     stderr=subprocess.DEVNULL,
        # )

        # Filter out binaries like latexmk, pdftex, etc.
        # progress.console.print("Fetching package metadata...")
        metadata_task = progress.add_task(
            description=f"Fetching metadata for {len(config.dependencies)} packages...",
            total=None,
        )
        progress.console.print(f"[dim]{', '.join(config.dependencies)}[/dim]")
        valid_dependencies, system_dependencies, already_installed = filter_packages(
            config.dependencies, env_dir, progress, metadata_task
        )
        progress.remove_task(metadata_task)
        all_dependencies = set(valid_dependencies + system_dependencies)
        progress.console.print(
            f"[dim]Skipping {len(already_installed)} already installed packages: {', '.join([pkg[0] for pkg in already_installed])}[/dim]"
        )
        install_task = progress.add_task(
            description=f"Installing {len(valid_dependencies)} packages...",
            total=None,
        )
        progress.console.print(
            f"[dim]Installing {len(valid_dependencies)} relocatable packages: {', '.join([pkg[0] for pkg in valid_dependencies])}[/dim]"
        )
        # cmd: list[str] = [
        #     "tlmgr",
        #     "install",
        #     "--usertree",
        #     str(env_dir),
        #     "--usermode",
        #     *config.dependencies,
        #     "--machine-readable",
        # ]

        # try:
        #     subprocess.run(cmd, check=True, capture_output=True, text=True)
        # except subprocess.CalledProcessError as e:
        #     console.print("[red]Package installation failed![/red]")
        #     console.print(e.stderr)
        #     raise typer.Exit(code=1)
        sorted_valid_dependencies = sorted(
            valid_dependencies, key=operator.itemgetter(0)
        )
        valid_dependencies = [pkg[0] for pkg in sorted_valid_dependencies]
        cmd: list[str] = [
            "tlmgr",
            "install",
            "--usertree",
            str(env_dir),
            "--usermode",
            *valid_dependencies,
            "--machine-readable",
        ]

        progress.console.print("[dim]Installing packages with tlmgr...[/dim]")
        install_process = subprocess.Popen(
            cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True
        )

        # install_process.
        ignore_output = False
        total = None
        for line in install_process.stdout:
            stripped_line = line.strip()
            if stripped_line.startswith("total-bytes"):
                parts = stripped_line.split("\t")
                if len(parts) >= 2:
                    total_bytes = parts[1]
                    # progress.console.print(
                    #     f"[dim]Total bytes to download: {total_bytes}[/dim]"
                    # )
                    total = int(total_bytes)
                    progress.update(install_task, total=total)
                    # progress.remove_task(install_task)
                    # install_task = progress.add_task(
                    #     description=f"Installing {len(valid_dependencies)} packages...\n",
                    #     total=total,
                    # )
            if "is not relocatable, cannot install it in user mode!" in stripped_line:
                parts = stripped_line.split()
                if len(parts) >= 2:
                    pkg_name = parts[2]
                    progress.console.print(
                        f"[yellow]Warning: Package '{pkg_name}' is not relocatable and cannot be installed in user mode. Skipping.[/yellow]"
                    )
                    # system_dependencies.append(pkg_name)

            if not ignore_output:
                # progress.console.print(stripped_line)
                if stripped_line.count("\t") == 9:
                    # progress.console.print(stripped_line.count("\t"))
                    parts = stripped_line.split("\t")
                    # progress.console.print(f"[dim]Parsed parts: {parts}[/dim]")
                    progress.advance(install_task, int(parts[4]))

            if stripped_line == "end-of-updates":
                # progress.update(install_task, completed=100)
                # progress.update(install_task, completed=total)
                progress.update(
                    install_task,
                    description="Running post-installation scripts...",
                    total=None,
                )
                ignore_output = True

        # if install_process.wait() != 0:
        # progress.console.print("[red]Package installation failed![/red]")
        # raise typer.Exit(code=1)
        # progress.update(install_task, completed=100)
        progress.console.print(
            f"[green]✔ Successfully synced {len(valid_dependencies)} dependencies into .texenv/[/green]"
            f"\n[dim]{', '.join(valid_dependencies)}[/dim]"
        )

        install_task = progress.add_task(
            description=f"Installing {len(system_dependencies)} system packages...\n[dim]{', '.join(system_dependencies)}[/dim]",
            total=None,
        )
        # cmd: list[str] = [
        #     "tlmgr",
        #     "install",
        #     "--usertree",
        #     str(env_dir),
        #     "--usermode",
        #     *config.dependencies,
        #     "--machine-readable",
        # ]

        # try:
        #     subprocess.run(cmd, check=True, capture_output=True, text=True)
        # except subprocess.CalledProcessError as e:
        #     console.print("[red]Package installation failed![/red]")
        #     console.print(e.stderr)
        #     raise typer.Exit(code=1)
        sorted_system_dependencies = sorted(
            system_dependencies, key=operator.itemgetter(0)
        )
        system_dependencies = [pkg[0] for pkg in sorted_system_dependencies]
        cmd: list[str] = [
            "tlmgr",
            "install",
            # "--usertree",
            # str(env_dir),
            # "--usermode",
            *system_dependencies,
            "--machine-readable",
        ]

        progress.console.print("[dim]Installing system packages with tlmgr...[/dim]")
        install_process = subprocess.Popen(
            cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True
        )

        ignore_output = False
        total = None
        for line in install_process.stdout:
            stripped_line = line.strip()
            if stripped_line.startswith("total-bytes"):
                parts = stripped_line.split("\t")
                if len(parts) >= 2:
                    total_bytes = parts[1]
                    progress.console.print(
                        f"[dim]Total bytes to download: {total_bytes}[/dim]"
                    )
                    total = int(total_bytes)
                    progress.update(install_task, total=total)
            if "is not relocatable, cannot install it in user mode!" in stripped_line:
                parts = stripped_line.split()
                if len(parts) >= 2:
                    pkg_name = parts[2]
                    progress.console.print(
                        f"[yellow]Warning: Package '{pkg_name}' is not relocatable and cannot be installed in user mode. Skipping.[/yellow]"
                    )
                    # system_dependencies.append(pkg_name)

            if not ignore_output:
                progress.console.print(stripped_line)
                if stripped_line.count("\t") == 9:
                    # progress.console.print(stripped_line.count("\t"))
                    parts = stripped_line.split("\t")
                    # progress.console.print(f"[dim]Parsed parts: {parts}[/dim]")
                    progress.advance(install_task, int(parts[4]))
                elif stripped_line.count("\t") >= 2:
                    progress.console.print(
                        f"[red]Unexpected tab output: {stripped_line}[/red]"
                    )

            if stripped_line == "end-of-updates":
                # progress.update(install_task, completed=100)
                # progress.update(install_task, completed=total)
                progress.update(
                    install_task,
                    description="Running post-installation scripts...",
                    total=None,
                )

                ignore_output = True
        # install_process.
        # for line in install_process.stdout:
        #     progress.console.print(line.strip())
        #     if line.strip() == "end-of-updates":
        #         progress.update(install_task, completed=100)

        # if install_process.wait() != 0:
        # progress.console.print("[red]Package installation failed![/red]")
        # raise typer.Exit(code=1)
    progress.update(
        install_task, completed=len(all_dependencies), total=len(all_dependencies)
    )
    progress.console.print(
        f"[green]✔ Successfully synced {len(all_dependencies)} dependencies into .texenv/[/green]"
        f"\n[dim]{', '.join([pkg[0] for pkg in all_dependencies])}[/dim]"
    )


@app.command()
def build() -> None:
    """Generates .latexmkrc and compiles the project."""
    cwd = Path.cwd()
    env_dir = cwd / ".texenv"

    output_file = cwd / "build" / "main.pdf"
    if output_file.exists():
        console.print(
            f"[dim]Removing existing output file: {output_file}[/dim]"
        )
        output_file.unlink()

    load_project_config(cwd / "texproject.toml")
    # generate_latexmkrc(config, cwd / ".latexmkrc")
    console.print("[dim]Generated .latexmkrc from texproject.toml[/dim]")

    env = os.environ.copy()
    if env_dir.exists():
        env["TEXMFHOME"] = str(env_dir.resolve())
        env["max_print_line"] = "100000"  # Avoid line wrapping in logs
        console.print("[dim]Using local .texenv for compilation[/dim]")
    else:
        console.print(
            "[yellow]Warning: .texenv not found. Run `texi sync` for isolated dependencies.[/yellow]"
        )

    console.print("[bold blue]Starting latexmk...[/bold blue]\n")
    try:
        subprocess.run(
            ["latexmk"], env=env, check=True, capture_output=False, text=True
        )
        console.print("\n[green]✔ Build completed successfully![/green]")
    except subprocess.CalledProcessError as e:
        console.print("\n[red]✖ Build failed. Check the logs above.[/red]")
        console.print(f"[dim]{e.stderr}[/dim]")
        raise typer.Exit(code=1)


if __name__ == "__main__":
    app()

# import subprocess
# import threading
# from typing import IO
# from rich.console import Console

# console = Console()

# def stream_reader(pipe: IO[str], stream_name: str, color: str) -> None:
#     """Reads lines from a subprocess pipe and prints them with a tag."""
#     # This loop runs until the subprocess closes the pipe
#     for line in pipe:
#         # Strip trailing newlines so rich doesn't double-space
#         clean_line = line.strip()
#         if clean_line:
#             console.print(f"[{color}][{stream_name}][/] {clean_line}")

# def run_command() -> None:
#     """Executes a command and streams stdout and stderr independently."""

#     # 1. Open the process with separate pipes
#     process = subprocess.Popen(
#         ["tlmgr", "update", "--list"],  # Example command
#         stdout=subprocess.PIPE,
#         stderr=subprocess.PIPE,
#         text=True
#     )

#     # 2. Assign a thread to watch each pipe
#     # We must assert process.stdout and stderr are not None for strict type checking
#     assert process.stdout is not None
#     assert process.stderr is not None

#     stdout_thread = threading.Thread(
#         target=stream_reader,
#         args=(process.stdout, "STDOUT", "green")
#     )
#     stderr_thread = threading.Thread(
#         target=stream_reader,
#         args=(process.stderr, "STDERR", "red")
#     )

#     # 3. Start watching
#     stdout_thread.start()
#     stderr_thread.start()

#     # 4. Wait for the streams to finish reading, then wait for the process to exit
#     stdout_thread.join()
#     stderr_thread.join()

#     exit_code = process.wait()

#     if exit_code != 0:
#         console.print(f"[bold red]Process failed with exit code {exit_code}[/bold red]")

# if __name__ == "__main__":
#     run_command()
